name: proyekakhir
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  getwidget: ^6.0.0
  get: ^4.6.5
  custom_radio_grouped_button: ^2.2.1
  provider: ^6.0.5
  intl: ^0.17.0
  path_provider: ^2.0.8
  hive: ^2.2.3  # Updated version to match hive_generator requirements
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.5.3
  google_maps_flutter: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15 # Keep only this in dev_dependencies
  hive_generator: ^2.0.1 # Ensure it is compatible with your Hive version
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
